# Generated by Django 5.0.6 on 2024-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='sip',
            field=models.CharField(default='sip', max_length=255),
        ),
    ]
