# Generated by Django 5.0.6 on 2024-07-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_sip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
